--Caso 1--
CREATE PROFILE prf_owner LIMIT
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LIFE_TIME 120;

CREATE PROFILE prf_desarrollador LIMIT
    CONNECT_TIME 240         
    IDLE_TIME 60             
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 1     
    PASSWORD_LIFE_TIME 90;

CREATE PROFILE prf_informes LIMIT
    CONNECT_TIME 120         
    IDLE_TIME 20             
    FAILED_LOGIN_ATTEMPTS 2
    PASSWORD_LOCK_TIME 1     
    PASSWORD_LIFE_TIME 90;

CREATE USER BDY1102_P9_1 IDENTIFIED BY "KoperaOwner_2026" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE prf_owner;
ALTER USER BDY1102_P9_1 QUOTA UNLIMITED ON USERS;

CREATE USER BDY1102_P9_2 IDENTIFIED BY "KoperaDevOne_2026" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE prf_desarrollador;
ALTER USER BDY1102_P9_2 QUOTA UNLIMITED ON USERS;

CREATE USER BDY1102_P9_3 IDENTIFIED BY "KoperaDevTwo_2026" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE prf_desarrollador;
ALTER USER BDY1102_P9_3 QUOTA UNLIMITED ON USERS;

CREATE USER BDY1102_P9_4 IDENTIFIED BY "KoperaTxRpt_2026" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE prf_informes;
ALTER USER BDY1102_P9_4 QUOTA 100M ON USERS;

CREATE USER BDY1102_P9_5 IDENTIFIED BY "KoperaCliOne_2026" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE prf_informes;
ALTER USER BDY1102_P9_5 QUOTA 100M ON USERS;

CREATE USER BDY1102_P9_6 IDENTIFIED BY "KoperaCliTwo_2026" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE prf_informes;
ALTER USER BDY1102_P9_6 QUOTA 100M ON USERS;

GRANT CREATE SESSION TO BDY1102_P9_1, BDY1102_P9_2, BDY1102_P9_3, BDY1102_P9_4, BDY1102_P9_5, BDY1102_P9_6;

GRANT CREATE TABLE, CREATE SEQUENCE TO BDY1102_P9_1;

GRANT CREATE PROCEDURE, CREATE TRIGGER, CREATE VIEW TO BDY1102_P9_2, BDY1102_P9_3; --aqui

DROP ROLE rol_desarrollo_kopera;
DROP ROLE rol_informes_tx;
DROP ROLE rol_informes_general;

CREATE ROLE rol_desarrollo_kopera;
CREATE ROLE rol_informes_tx;
CREATE ROLE rol_informes_general;

GRANT SELECT ON BDY1102_P9_1.CLIENTE TO rol_desarrollo_kopera;
GRANT SELECT ON BDY1102_P9_1.COMUNA TO rol_desarrollo_kopera;
GRANT SELECT ON BDY1102_P9_1.REGION TO rol_desarrollo_kopera;
GRANT SELECT, INSERT, UPDATE, DELETE ON BDY1102_P9_1.CREDITO_CLIENTE TO rol_desarrollo_kopera;
GRANT SELECT, INSERT, UPDATE, DELETE ON BDY1102_P9_1.PRODUCTO_INVERSION_CLIENTE TO rol_desarrollo_kopera;
GRANT SELECT, INSERT, UPDATE, DELETE ON BDY1102_P9_1.CUOTA_CREDITO_CLIENTE TO rol_desarrollo_kopera;


GRANT SELECT ON BDY1102_P9_1.TIPO_MOVIMIENTO TO rol_informes_tx;
GRANT SELECT ON BDY1102_P9_1.SUCURSAL TO rol_informes_tx;
GRANT SELECT ON BDY1102_P9_1.TIPO_CONTRATO TO rol_informes_tx;
GRANT SELECT ON BDY1102_P9_1.CLIENTE TO rol_informes_tx;
GRANT SELECT ON BDY1102_P9_1.REGION TO rol_informes_tx;
GRANT SELECT ON BDY1102_P9_1.PROVINCIA TO rol_informes_tx;
GRANT SELECT ON BDY1102_P9_1.COMUNA TO rol_informes_tx;

GRANT SELECT ON BDY1102_P9_1.CLIENTE TO rol_informes_general;
GRANT SELECT ON BDY1102_P9_1.REGION TO rol_informes_general;
GRANT SELECT ON BDY1102_P9_1.PROVINCIA TO rol_informes_general;
GRANT SELECT ON BDY1102_P9_1.COMUNA TO rol_informes_general;

GRANT rol_desarrollo_kopera TO BDY1102_P9_2, BDY1102_P9_3;
GRANT rol_informes_tx TO BDY1102_P9_4;
GRANT rol_informes_general TO BDY1102_P9_5, BDY1102_P9_6;

CREATE OR REPLACE PUBLIC SYNONYM SYN_CLIENTE FOR BDY1102_P9_1.CLIENTE;
CREATE OR REPLACE PUBLIC SYNONYM SYN_COMUNA FOR BDY1102_P9_1.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_REGION FOR BDY1102_P9_1.REGION;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PROVINCIA FOR BDY1102_P9_1.PROVINCIA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_SUCURSAL FOR BDY1102_P9_1.SUCURSAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TIPO_CONTRATO FOR BDY1102_P9_1.TIPO_CONTRATO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TIPO_MOVIMIENTO FOR BDY1102_P9_1.TIPO_MOVIMIENTO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CREDITO_CLIENTE FOR BDY1102_P9_1.CREDITO_CLIENTE;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PRODUCTO_INVERSION_CLIENTE FOR BDY1102_P9_1.PRODUCTO_INVERSION_CLIENTE;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CUOTA_CREDITO_CLIENTE FOR BDY1102_P9_1.CUOTA_CREDITO_CLIENTE;

GRANT SELECT ON BDY1102_P9_1.CLIENTE TO BDY1102_P9_2 WITH GRANT OPTION;
GRANT SELECT ON BDY1102_P9_1.CREDITO_CLIENTE TO BDY1102_P9_2 WITH GRANT OPTION;

GRANT SELECT ON BDY1102_P9_1.CLIENTE TO BDY1102_P9_3 WITH GRANT OPTION;
GRANT SELECT ON BDY1102_P9_1.COMUNA TO BDY1102_P9_3 WITH GRANT OPTION;
GRANT SELECT ON BDY1102_P9_1.REGION TO BDY1102_P9_3 WITH GRANT OPTION;