ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER BDY1102_P8 IDENTIFIED BY "BDY1102_P8.practica_8"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P8 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P8;
GRANT "RESOURCE" TO BDY1102_P8;
ALTER USER BDY1102_P8 DEFAULT ROLE "RESOURCE";
GRANT CREATE VIEW TO BDY1102_P8;