ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER BDY1102E3_FE IDENTIFIED BY "EVALUACION_3.practica2026"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102E3_FE QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102E3_FE;
GRANT "RESOURCE" TO BDY1102E3_FE;
ALTER USER BDY1102E3_FE DEFAULT ROLE "RESOURCE";