ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER BDY1102E3 IDENTIFIED BY "EVALUACION_3.practica2026"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102E3 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102E3;
GRANT "RESOURCE" TO BDY1102E3;
ALTER USER BDY1102E3 DEFAULT ROLE "RESOURCE";

