ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER BDY1102_P5 IDENTIFIED BY "BDY1102_P5.practica_5"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P5 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P5;
GRANT "RESOURCE" TO BDY1102_P5;
ALTER USER BDY1102_P5 DEFAULT ROLE "RESOURCE";
