ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
CREATE USER BDY1102_P2 IDENTIFIED BY "BDY1102_P2.practica_2"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P2 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P2;
GRANT RESOURCE TO BDY1102_P2;
ALTER USER BDY1102_P2 DEFAULT ROLE RESOURCE;