ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER  BDY1102_P4 IDENTIFIED BY "BDY1102_P4.practica_4"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P4 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P4;
GRANT "RESOURCE" TO BDY1102_P4;
ALTER USER BDY1102_P4 DEFAULT ROLE "RESOURCE";